version: '1'
services:
  open-innovation-ai-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - DOCKER=True
      - MONGODB_LOCAL_URI=mongodb://host.docker.internal:27017/
      - MONGODB_DOCKER_URI=mongodb://localhost:27017/
      - DB_NAME=OpenInnovationAIImageDB
      - IMG_DATA_PATH=data